#PMMPでマルチをするときのチーム分け用プラグイン
name: TeamPlugin
main: team\team
version: 0.0.2
api: 3.0.0-ALPHA11

commands:
 team:
  description: "team"
  usage: " /team [操作] [チーム名] \n操作は make:作成 delete:削除"

 join:
  description: "join team"
  usage: " /join [チーム名]"

 leave:
  description: "leave team"
  usage: " /leave"
 
permissions:
 team:
  default: OP
  description: "Allows making and deleting teams"
  children:
   team.command:
    default: true
    description: "Allows making and deleting teams"

 joinleave:
  default: true
  description: "Allows joining and leaving teams"
  children:
   jl.command:
    default: true
    description: "Allows joining and leaving teams"